{% set name = "pyrad_arm" %}
{% set version = "0.5.0" %}
{% set sha256 = "5591885639efe4ca78eb47b30448e52ccb37ab2ad67840ba89a2d656f0c4bcc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrad_mch/pyrad_mch-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py2k or win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - arm_pyart

test:
  imports:
    - pyrad

about:
  home: https://pyrad-mch.readthedocs.io/en/stable/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MeteoSwiss Pyrad, Python tool for radar data processing.
  description: |
    This is the MeteoSwiss Pyrad. Pyrad is an open source Python
    module for weather radar data processing. The module controls the
    data flow. The inputs and outputs are specified using config files.
    Most of the core data processing is performed using Py-ART, originally
    developed in the framework of the Atmospheric Radiation Measurement (ARM)
    Climate Research Facility for working with data from a number of
    precipitation and cloud radars. This package is provided for convenience
    to the Py-ART comunity. If you would like to get the full functionality of
    Pyrad please use pyrad_mch, which runs with the MeteoSwiss version of
    Py-ART.
  doc_url: https://pyrad-mch.readthedocs.io/en/stable/
  dev_url: https://github.com/MeteoSwiss/pyrad

extra:
  recipe-maintainers:
    - meteoswiss-mdr
